openapi: 3.0.3
info:
  title: Auth API
  description: API for user registration, authentication, and fetching user details
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationData'
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Registration failed
  /authenticate:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthData'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: Authentication failed
  /get_user:
    get:
      summary: Get user data
      responses:
        '200':
          description: Successfully retrieved user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetails'
        '400':
          description: Failed to retrieve user data
components:
  schemas:
    RegistrationData:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
          format: date
        email:
          type: string
          format: email
        phone_number:
          type: string
        username:
          type: string
        password:
          type: string
      required: 
        - first_name
        - last_name
        - birth_date
        - email
        - phone_number
        - username
        - password
      
    AuthData:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    
    UserDetails:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
          format: date
        email:
          type: string
          format: email
        phone_number:
          type: string
        username:
          type: string

    Response:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string