# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"D\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"8\n\x14\x41uthenticateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x8f\x01\n\x0cUserResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x12\n\nbirth_date\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x14\n\x0cphone_number\x18\x06 \x01(\t\x12\x10\n\x08username\x18\x07 \x01(\t\"\x88\x01\n\x14ProfileUpdateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x12\n\nbirth_date\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x14\n\x0cphone_number\x18\x06 \x01(\t\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x97\x02\n\x0b\x41uthService\x12=\n\x0cRegisterUser\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x12I\n\x10\x41uthenticateUser\x12\x19.auth.AuthenticateRequest\x1a\x1a.auth.AuthenticateResponse\x12\x37\n\x0eGetUserDetails\x12\x11.auth.UserRequest\x1a\x12.auth.UserResponse\x12\x45\n\x11UpdateUserProfile\x12\x1a.auth.ProfileUpdateRequest\x1a\x14.auth.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=88
  _globals['_REGISTERRESPONSE']._serialized_start=90
  _globals['_REGISTERRESPONSE']._serialized_end=142
  _globals['_AUTHENTICATEREQUEST']._serialized_start=144
  _globals['_AUTHENTICATEREQUEST']._serialized_end=201
  _globals['_AUTHENTICATERESPONSE']._serialized_start=203
  _globals['_AUTHENTICATERESPONSE']._serialized_end=259
  _globals['_USERREQUEST']._serialized_start=261
  _globals['_USERREQUEST']._serialized_end=292
  _globals['_USERRESPONSE']._serialized_start=295
  _globals['_USERRESPONSE']._serialized_end=438
  _globals['_PROFILEUPDATEREQUEST']._serialized_start=441
  _globals['_PROFILEUPDATEREQUEST']._serialized_end=577
  _globals['_UPDATERESPONSE']._serialized_start=579
  _globals['_UPDATERESPONSE']._serialized_end=629
  _globals['_AUTHSERVICE']._serialized_start=632
  _globals['_AUTHSERVICE']._serialized_end=911
# @@protoc_insertion_point(module_scope)
