# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 29, 0, '', 'posts.proto')
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bposts.proto\x12\x05posts\"m\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"3\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncreator_id\x18\x02 \x01(\t\"y\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x12\n\ncreator_id\x18\x06 \x01(\t\"0\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncreator_id\x18\x02 \x01(\t\"N\n\x10ListPostsRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\ncreator_id\x18\x03 \x01(\t\"K\n\x0cPostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x04post\x18\x03 \x01(\x0b\x32\x0b.posts.Post\"Q\n\x11ListPostsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x05posts\x18\x03 \x03(\x0b\x32\x0b.posts.Post\"\x94\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreator_id\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t2\xc5\x02\n\x0bPostService\x12=\n\nCreatePost\x12\x18.posts.CreatePostRequest\x1a\x13.posts.PostResponse\"\x00\x12=\n\nDeletePost\x12\x18.posts.DeletePostRequest\x1a\x13.posts.PostResponse\"\x00\x12=\n\nUpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x13.posts.PostResponse\"\x00\x12\x37\n\x07GetPost\x12\x15.posts.GetPostRequest\x1a\x13.posts.PostResponse\"\x00\x12@\n\tListPosts\x12\x17.posts.ListPostsRequest\x1a\x18.posts.ListPostsResponse\"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_CREATEPOSTREQUEST']._serialized_start = 22
    _globals['_CREATEPOSTREQUEST']._serialized_end = 131
    _globals['_DELETEPOSTREQUEST']._serialized_start = 133
    _globals['_DELETEPOSTREQUEST']._serialized_end = 184
    _globals['_UPDATEPOSTREQUEST']._serialized_start = 186
    _globals['_UPDATEPOSTREQUEST']._serialized_end = 307
    _globals['_GETPOSTREQUEST']._serialized_start = 309
    _globals['_GETPOSTREQUEST']._serialized_end = 357
    _globals['_LISTPOSTSREQUEST']._serialized_start = 359
    _globals['_LISTPOSTSREQUEST']._serialized_end = 437
    _globals['_POSTRESPONSE']._serialized_start = 439
    _globals['_POSTRESPONSE']._serialized_end = 514
    _globals['_LISTPOSTSRESPONSE']._serialized_start = 516
    _globals['_LISTPOSTSRESPONSE']._serialized_end = 597
    _globals['_POST']._serialized_start = 600
    _globals['_POST']._serialized_end = 748
    _globals['_POSTSERVICE']._serialized_start = 751
    _globals['_POSTSERVICE']._serialized_end = 1076
# @@protoc_insertion_point(module_scope)
