syntax = "proto3";

package posts;

service PostService {
    rpc CreatePost (CreatePostRequest) returns (PostResponse) {}
    rpc DeletePost (DeletePostRequest) returns (PostResponse) {}
    rpc UpdatePost (UpdatePostRequest) returns (PostResponse) {}
    rpc GetPost (GetPostRequest) returns (PostResponse) {}
    rpc ListPosts (ListPostsRequest) returns (ListPostsResponse) {}
    rpc LikePost (LikePostRequest) returns (LikePostResponse) {}
    rpc UnlikePost (LikePostRequest) returns (LikePostResponse) {}
    rpc LeaveComment (LeaveCommentRequest) returns (LeaveCommentResponse) {}
    rpc ListComments (ListCommentsRequest) returns (ListCommentsResponse) {}
}

message CreatePostRequest {
    string title = 1;
    string description = 2;
    string creator_id = 3;
    bool is_private = 4;
    repeated string tags = 5;
}

message DeletePostRequest {
    int32 id = 1;
    string creator_id = 2;
}

message UpdatePostRequest {
    int32 id = 1;
    string title = 2;
    string description = 3;
    bool is_private = 4;
    repeated string tags = 5;
    string creator_id = 6;
}

message GetPostRequest {
    int32 id = 1;
    string creator_id = 2;
}

message ListPostsRequest {
    int32 page_number = 1;
    int32 page_size = 2;
    string creator_id = 3;
    string author_id = 4;
}

message PostResponse {
    bool success = 1;
    string message = 2;
    Post post = 3;
}

message ListPostsResponse {
    bool success = 1;
    string message = 2;
    repeated Post posts = 3;
}

message Post {
    int32 id = 1;
    string title = 2;
    string description = 3;
    string creator_id = 4;
    string created_at = 5;
    string updated_at = 6;
    bool is_private = 7;
    repeated string tags = 8;
}

message LikePostRequest {
    int32 post_id = 1;
    string creator_id = 2;
}

message LikePostResponse {
    bool success = 1;
    string message = 2;
}

message LeaveCommentRequest {
    int32 post_id = 1;
    string creator_id = 2;
    string text = 3;
}

message LeaveCommentResponse {
    bool success = 1;
    string message = 2;
    Comment comment = 3;
}

message ListCommentsRequest {
    int32 post_id = 1;
    int32 page_number = 2;
    int32 page_size = 3;
    string creator_id = 4;
}

message ListCommentsResponse {
    bool success = 1;
    string message = 2;
    repeated Comment comments = 3;
}

message Comment {
    int32 id = 1;
    int32 post_id = 2;
    string creator_id = 3;
    string text = 4;
    string created_at = 5;
}