version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - user
    environment:
      - API_SERVER_PORT=5000
      - USER_GRPC_SERVER_HOST=user
      - USER_GRPC_SERVER_PORT=50051

  user:
    build: ./user
    ports:
      - "50051:50051"
    environment:
      POSTGRES_DB: user_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DATABASE_URL: "postgresql://myuser:mypassword@user_db:5432/user_database"
    depends_on:
      - user_db

  user_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
